//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rtcc.PayByCell {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PayByCell.GetActiveParkingInformationSoap")]
    public interface GetActiveParkingInformationSoap {
        
        // CODEGEN: Generating message contract since element name poleSerNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddParkingForPayByCell", ReplyAction="*")]
        Rtcc.PayByCell.AddParkingForPayByCellResponse AddParkingForPayByCell(Rtcc.PayByCell.AddParkingForPayByCellRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddParkingForPayByCellRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddParkingForPayByCell", Namespace="http://tempuri.org/", Order=0)]
        public Rtcc.PayByCell.AddParkingForPayByCellRequestBody Body;
        
        public AddParkingForPayByCellRequest() {
        }
        
        public AddParkingForPayByCellRequest(Rtcc.PayByCell.AddParkingForPayByCellRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddParkingForPayByCellRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long accountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int poleID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string poleSerNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime startDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int purchasedTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string authCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string phoneNumber;
        
        public AddParkingForPayByCellRequestBody() {
        }
        
        public AddParkingForPayByCellRequestBody(long accountNumber, int poleID, string poleSerNo, System.DateTime startDateTime, double amount, int purchasedTime, string authCode, string phoneNumber) {
            this.accountNumber = accountNumber;
            this.poleID = poleID;
            this.poleSerNo = poleSerNo;
            this.startDateTime = startDateTime;
            this.amount = amount;
            this.purchasedTime = purchasedTime;
            this.authCode = authCode;
            this.phoneNumber = phoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddParkingForPayByCellResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddParkingForPayByCellResponse", Namespace="http://tempuri.org/", Order=0)]
        public Rtcc.PayByCell.AddParkingForPayByCellResponseBody Body;
        
        public AddParkingForPayByCellResponse() {
        }
        
        public AddParkingForPayByCellResponse(Rtcc.PayByCell.AddParkingForPayByCellResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddParkingForPayByCellResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddParkingForPayByCellResult;
        
        public AddParkingForPayByCellResponseBody() {
        }
        
        public AddParkingForPayByCellResponseBody(bool AddParkingForPayByCellResult) {
            this.AddParkingForPayByCellResult = AddParkingForPayByCellResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetActiveParkingInformationSoapChannel : Rtcc.PayByCell.GetActiveParkingInformationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetActiveParkingInformationSoapClient : System.ServiceModel.ClientBase<Rtcc.PayByCell.GetActiveParkingInformationSoap>, Rtcc.PayByCell.GetActiveParkingInformationSoap {
        
        public GetActiveParkingInformationSoapClient() {
        }
        
        public GetActiveParkingInformationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetActiveParkingInformationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetActiveParkingInformationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetActiveParkingInformationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rtcc.PayByCell.AddParkingForPayByCellResponse Rtcc.PayByCell.GetActiveParkingInformationSoap.AddParkingForPayByCell(Rtcc.PayByCell.AddParkingForPayByCellRequest request) {
            return base.Channel.AddParkingForPayByCell(request);
        }
        
        public bool AddParkingForPayByCell(long accountNumber, int poleID, string poleSerNo, System.DateTime startDateTime, double amount, int purchasedTime, string authCode, string phoneNumber) {
            Rtcc.PayByCell.AddParkingForPayByCellRequest inValue = new Rtcc.PayByCell.AddParkingForPayByCellRequest();
            inValue.Body = new Rtcc.PayByCell.AddParkingForPayByCellRequestBody();
            inValue.Body.accountNumber = accountNumber;
            inValue.Body.poleID = poleID;
            inValue.Body.poleSerNo = poleSerNo;
            inValue.Body.startDateTime = startDateTime;
            inValue.Body.amount = amount;
            inValue.Body.purchasedTime = purchasedTime;
            inValue.Body.authCode = authCode;
            inValue.Body.phoneNumber = phoneNumber;
            Rtcc.PayByCell.AddParkingForPayByCellResponse retVal = ((Rtcc.PayByCell.GetActiveParkingInformationSoap)(this)).AddParkingForPayByCell(inValue);
            return retVal.Body.AddParkingForPayByCellResult;
        }
    }
}
