//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizationClientPlatforms.IsraelProcessor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IsraelProcessor.IIsraelProcessorService")]
    public interface IIsraelProcessorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIsraelProcessorService/AuthCreditCardFull", ReplyAction="http://tempuri.org/IIsraelProcessorService/AuthCreditCardFullResponse")]
        int AuthCreditCardFull(
                    out string TransactionRecord, 
                    out string ResultRecord, 
                    string premiumUserName, 
                    string premiumPassword, 
                    string premiumCashierNum, 
                    string merchantNumber, 
                    string transactionDate_yyyyMMdd, 
                    string transactionTime_HHmm, 
                    string uniqueTransactionNumber_SixDigits, 
                    string track2, 
                    string cardNum, 
                    string expDate_YYMM, 
                    string amount, 
                    string cochavAmount, 
                    string transactionType, 
                    string creditTerms, 
                    string currency, 
                    string authNum, 
                    string code, 
                    string firstAmount, 
                    string nonFirstAmount, 
                    string numOfPayment, 
                    string sapakMutav, 
                    string sapakMutavNo, 
                    string uniqNum, 
                    string clubCode, 
                    string paramJ, 
                    string addData, 
                    string eci, 
                    string cvv2, 
                    string id, 
                    string cavvUcaf, 
                    string last4Digits, 
                    string transactionCurrency, 
                    string transactionAmount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIsraelProcessorServiceChannel : AuthorizationClientPlatforms.IsraelProcessor.IIsraelProcessorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsraelProcessorServiceClient : System.ServiceModel.ClientBase<AuthorizationClientPlatforms.IsraelProcessor.IIsraelProcessorService>, AuthorizationClientPlatforms.IsraelProcessor.IIsraelProcessorService {
        
        public IsraelProcessorServiceClient() {
        }
        
        public IsraelProcessorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsraelProcessorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsraelProcessorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsraelProcessorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AuthCreditCardFull(
                    out string TransactionRecord, 
                    out string ResultRecord, 
                    string premiumUserName, 
                    string premiumPassword, 
                    string premiumCashierNum, 
                    string merchantNumber, 
                    string transactionDate_yyyyMMdd, 
                    string transactionTime_HHmm, 
                    string uniqueTransactionNumber_SixDigits, 
                    string track2, 
                    string cardNum, 
                    string expDate_YYMM, 
                    string amount, 
                    string cochavAmount, 
                    string transactionType, 
                    string creditTerms, 
                    string currency, 
                    string authNum, 
                    string code, 
                    string firstAmount, 
                    string nonFirstAmount, 
                    string numOfPayment, 
                    string sapakMutav, 
                    string sapakMutavNo, 
                    string uniqNum, 
                    string clubCode, 
                    string paramJ, 
                    string addData, 
                    string eci, 
                    string cvv2, 
                    string id, 
                    string cavvUcaf, 
                    string last4Digits, 
                    string transactionCurrency, 
                    string transactionAmount) {
            return base.Channel.AuthCreditCardFull(out TransactionRecord, out ResultRecord, premiumUserName, premiumPassword, premiumCashierNum, merchantNumber, transactionDate_yyyyMMdd, transactionTime_HHmm, uniqueTransactionNumber_SixDigits, track2, cardNum, expDate_YYMM, amount, cochavAmount, transactionType, creditTerms, currency, authNum, code, firstAmount, nonFirstAmount, numOfPayment, sapakMutav, sapakMutavNo, uniqNum, clubCode, paramJ, addData, eci, cvv2, id, cavvUcaf, last4Digits, transactionCurrency, transactionAmount);
        }
    }
}
