//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rtcc.ReceiptService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://www.ipsmetersystems.com/ReceiptingSystem")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionRecordIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCHash {
            get {
                return this.CCHashField;
            }
            set {
                if ((object.ReferenceEquals(this.CCHashField, value) != true)) {
                    this.CCHashField = value;
                    this.RaisePropertyChanged("CCHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionRecordID {
            get {
                return this.TransactionRecordIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionRecordIDField, value) != true)) {
                    this.TransactionRecordIDField = value;
                    this.RaisePropertyChanged("TransactionRecordID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReceiptService.IValidateCard")]
    public interface IValidateCard {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidateCard/SubmitReqest", ReplyAction="http://tempuri.org/IValidateCard/SubmitReqestResponse")]
        void SubmitReqest(Rtcc.ReceiptService.Transaction objTransaction);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidateCardChannel : Rtcc.ReceiptService.IValidateCard, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateCardClient : System.ServiceModel.ClientBase<Rtcc.ReceiptService.IValidateCard>, Rtcc.ReceiptService.IValidateCard {
        
        public ValidateCardClient() {
        }
        
        public ValidateCardClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateCardClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCardClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCardClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitReqest(Rtcc.ReceiptService.Transaction objTransaction) {
            base.Channel.SubmitReqest(objTransaction);
        }
    }
}
