//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebserverTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISmartPayNotificationService")]
    public interface ISmartPayNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartPayNotificationService/SmartPayNotification", ReplyAction="http://tempuri.org/ISmartPayNotificationService/SmartPayNotificationResponse")]
        string SmartPayNotification(string payload);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartPayNotificationService/SmartPayNotification", ReplyAction="http://tempuri.org/ISmartPayNotificationService/SmartPayNotificationResponse")]
        System.Threading.Tasks.Task<string> SmartPayNotificationAsync(string payload);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmartPayNotificationServiceChannel : WebserverTest.ServiceReference1.ISmartPayNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartPayNotificationServiceClient : System.ServiceModel.ClientBase<WebserverTest.ServiceReference1.ISmartPayNotificationService>, WebserverTest.ServiceReference1.ISmartPayNotificationService {
        
        public SmartPayNotificationServiceClient() {
        }
        
        public SmartPayNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartPayNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartPayNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartPayNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SmartPayNotification(string payload) {
            return base.Channel.SmartPayNotification(payload);
        }
        
        public System.Threading.Tasks.Task<string> SmartPayNotificationAsync(string payload) {
            return base.Channel.SmartPayNotificationAsync(payload);
        }
    }
}
