..\QuerySchema\Bin\Debug\QuerySchema UPD_TRANSACTIONRECORD_CCTM_FINALIZATION> UPD_TRANSACTIONRECORD_CCTM_FINALIZATION.txt
..\QuerySchema\Bin\Debug\QuerySchema UPD_TRANSACTIONRECORD_STATUS > UPD_TRANSACTIONRECORD_STATUS.txt
..\QuerySchema\Bin\Debug\QuerySchema UPD_TRANSACTIONAUTHORIZATION_STATUS > UPD_TRANSACTIONAUTHORIZATION_STATUS.txt
..\QuerySchema\Bin\Debug\QuerySchema SEL_NEW_TRANSACTIONRECORDS > SEL_NEW_TRANSACTIONRECORDS.txt
..\QuerySchema\Bin\Debug\QuerySchema UPD_TRANSACTIONAUTHORIZATION > UPD_TRANSACTIONAUTHORIZATION.txt